== Chapter 2. Sabbath and the First (and Second) Commandment

=== Summary.

==== Intro.

Sabbath-keeping is
. a way of making a peculiar identify amid a larger public identify
. of maintaining and enacting a counter-identify that refuses "`mainstream`" identity,
.. of which itself entails anti-human practice and the worship of anti-human gods.

Understood in this way, Sabbath is a
. bodily
. act of
. testimony testimony
. alternative and
. resistance to pervading values and the assumptions behind those values.

==== 1. The 10 Commandments

After the Exodus, Israel received and swore allegiance to the new commands of YHWH that were in start contrast to the commands of Pharaoh.

==== 2. The world of Pharaoh

. Pharaoh was a god--absolute authority.
. Egypt's socioeconomic power was organized like a pyramid, with all wealth flowing upwards to the elite and, eventually, to Pharaoh.
. Yet, that Pharaoh was anxious, making others anxious and creating a culture of anxiety.
. Scarcity led to rapacious and exploitative state policies of monopoly, making everyone slaves.
. Thus, people were unhappy.

Yet! God was the one "`who brought [Israelites] out of the land of Egypt, out of the house of slavery.`"

==== 3. God vs. Pharaoh

God had the exclusive rights to Israelites. Yet, this "`exclusivity of YHWH was different because of what followed`"--"`God spoke six times about the neighbour`".
. 5th to 10th commands were quite unlike any decree of Pharaoh because it includes the neighbour in the social calculus and dares to imagine the maintenance of a neighbourly community."``"

Q. How does one regard the neighbour seriously when one has imbibed the profound anxiety of the Egyptian system?
A. Sabbath! "`There had been no Sabbath in Egypt.`"

"`The [production] limit is set by the weekly work pause that breaks the production cycle. And those who participate in it break the anxiety cycle. They are invited`"
. to awareness that life does not consist in frantic production and consumption that reduces everyone else to threat and competitor.
. to enery redeployed to neighbourhood.

God counters anxious productivity with committed neighbourliness, and He creates an environment of security and respect and dignity that redefines the human project.

==== 4. Why Sabbath?

God rested on the seventh day and enjoyed stoppage!
. God has complete confidence in the fruit-bearing, blessing-generating processes of creation that have been instituted.
. God exhibits no anxiety about the life-giving capacity of creation.
. (Promise?) Humankind will govern the earth in a generative way. All will be well, and all manner of thing will be well because... God!

The world is an anxiety-free one of well-being because the creator is anxiety-free and publicly exhibits that freedom from anxiety by not checking things out.
. He is not a workaholic, Pharaoh, or a maneger who keep jacking up production schedules.
. God rests, confident, serene, and at peace.
.. His rest bestows on creatureliness a restfulness that contradicts the "`drivenness`" of the system of Pharaoh.

==== 5. Commands on Neighbourliness

We are God's image!
. Rest like God!
. While resting, be sure that the neighbours rest alongside!
. Sponsor a system of rest that contradicts the system of anxiety, because we are not subjects of Pharaoh.
. Create restfulness with theological rootage, political viability, and economic significance for all in the domain of covenant (Q. 4 days workweek, basic universal income, technological advancements)
