== Chapter 3. Resistance to Coercion

=== Summary

==== Intro

. Sabbath requires faith!
.. Israelites apostatized as anxiety grew bigger, for Moses was nowhere to be found.
.. Though the covenant was nullified, a new different set of commands were given.
... Yet, Sabbath overlapped. Moreover, Israelites were to rest in both plowing times and harest times.

==== Wanring 

. Moses warns Israelites not to forget Sabbath and the neighbourliness that follows.
. Land as Inheritance vs. Land as Property
.. Economy as covenantal enterprise for the sake of the whole community

==== Sabbath and Neighbourliness

. All households (including the domesticated animals and slaves) were to rest like the master.
.. "Sabbath is the great day of equality when all are equally at rest."
. Coercion in a society defined by production and consumption, performance is graded.
.. Thus, worth and significance are given to those who produce more.
.. This is implicit form of coersion!
. But! Sabbath breaks down the gradation. On the Sabbath,
.. People do not have to do more.
.. People do not have to sell more.
.. People do not have to control more.
.. People do not have to know more.
.. People do not have to have their kids in ballet or soccer.
.. People do not have to be younger or more beautiful.
.. People do not have te score more.
. In Exodus, the motivation was the creation account. In Deuteronomy, it is Exodus.
.. Exodus was when all coercions were broken!

==== Sabbath as a New Social Reality

. Moses imagines that Sabbath is not only a festival day but also a new social reality that is carried back into days one through six.
.. Every seventh year, people are liberated and equalized
.. The disadventaged shall rest like all the others

